### PR TITLE
Add tests scenarios for trivy scanning

### PR DESCRIPTION
**Pull request by JAORMX**
This tests a couple of scenarios for security issues:

* The default configuration
* A configuration where an image is used to import the endpoints.

Signed-off-by: Juan Antonio Osorio <juan.osoriorobles@eu.equinix.com>

### CODE REVIEW

**Review by hnadiminti-equinix — COMMENTED** [review]
Seeing it few medium vulnerabilities 🤔

**Comment by JAORMX** [comment]
@hnadiminti-equinix right now we're only failing the job on `HIGH` and `CRITICAL vulnerabilities. I'll address the `MEDIUM` ones in a subsequent PR.

**Comment by hnadiminti-equinix** [comment]
> @hnadiminti-equinix right now we're only failing the job on `HIGH` and `CRITICAL` vulnerabilities. I'll address the `MEDIUM` ones in a subsequent PR.

**Review by hnadiminti-equinix — APPROVED** [review]
Okay, It looks good to me.

**Pull request merged**
