### PR TITLE
Release v0.1.31

### PR DESCRIPTION
**Pull request by JAORMX**

### CODE REVIEW

**Comment by rsicart** [comment]
Do you have some news about this release please?

Thanks in advance!

**Comment by JAORMX** [comment]
@rsicart waiting for someone to merge this. I can't self-merge.

**Comment by JAORMX** [comment]
@tylerauerbeck @fishnix can you check this out?

**Comment by rsicart** [comment]
If that can help,

Comparing with the diff of the last release, LGTM :+1:

**Pull request closed without merging**
